spring.application.name=vlogi

spring.datasource.url=jdbc:mariadb://localhost:3306/db_articles?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=vlogiNPTV23
spring.datasource.password=vlogiNPTV23

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=true
logging.level.org.springframework=DEBUG
